name: Build and Deploy to AWS

on:
  push:
    branches:
      - production

env:
  AWS_REGION: ap-southeast-1
  ECR_WEB_REPO: chat-app-web
  ECR_SERVER_REPO: chat-app-server
  ECS_CLUSTER: chat-app-cluster
  ECS_SERVICE: chat-app-service
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Web Image
        run: |
          docker build \
            --target web \
            --build-arg NEXT_PUBLIC_API_URL=https://${{ secrets.ALB_DNS_NAME }} \
            --build-arg NEXT_PUBLIC_METERED_API_KEY=${{ secrets.METERED_API_KEY }} \
            -t ${{ secrets.AWS_ECR_WEB_REPO}} .
          docker push ${{ secrets.AWS_ECR_WEB_REPO}}
      - name: Build & Push Server Image
        run: |
          docker build --target server -t ${{ secrets.AWS_ECR_SERVER_REPO}} . 
          docker push ${{ secrets.AWS_ECR_SERVER_REPO}}

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
              --cluster ${{ secrets.AWS_ECS_CLUSTER }} \
              --service ${{ secrets.AWS_ECS_WEB_SERVICE }} \
              --force-new-deployment \
              --region ${{ secrets.AWS_REGION }} \
              --desired-count 1
